# This workflow will publish a release with a usuable blender addon build for
# windows and linux. This is accomplished roughly with the steps below:
# - go into /home/runner/work/b_x_utils/b_x_utils with ${{ github.workspace }}
# - make sure cpython is cloned with git submodule init/update
# - compile zig module
# - zip up the directory with the included build while excluding unnecessary files.
name: Publish
on:
  push:
    tags:
      - "v*"
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v6
      - uses: mlugg/setup-zig@v2
      - run: |
          cd ${{ github.workspace }}
          git submodule init && git submodule update
          cd py_modules/zig_modules/src
          zig build --release=small -p .. --prefix-lib-dir .
          cd ../../../..
          zip -r b_x_utils b_x_utils -x "*.rfc" "*.rdb" "b_x_utils/.git/*" "b_x_utils/.github/*" "b_x_utils/.gitmodules" "b_x_utils/.gitignore" "b_x_utils/py_modules/zig_modules/src/*"
          gh release create ${{ github.ref_name}} b_x_utils.zip
